# Generated by Django 4.0.2 on 2022-03-23 19:39

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectlistpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlistpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
