# Generated by Django 4.1.7 on 2023-03-06 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("projects", "0004_project_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="hero_image",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="wagtailimages.image"
            ),
        ),
    ]
