pull_request_rules:
- name: Merge Updates
  conditions:
  - and:
    - author~=^github-actions
    - title~=^Updates
  actions:
    merge:
      method: merge
- name: Merge Mine
  conditions:
  - and:
    - author~=^bengosney$
  actions:
    merge:
      method: merge
- name: Automatic merge dependabot PR
  conditions:
  - author~=^dependabot(|-preview)\[bot\]$
  actions:
    merge:
      method: merge
