pull_request_rules:
  - name: Merge Mine
    conditions:
      - author~=^bengosney$
      - check-success=workflow
      - check-success=Sourcery
      - check-success~=^Analyze
    actions:
      merge:
        method: merge

  - name: Automatic merge dependabot PR
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=workflow
    actions:
      merge:
        method: merge

  - name: Automatic merge on approval of Sourcery AI PR
    conditions:
      - author~=^sourcery.*$
      - check-success=workflow
      - check-success~=^Analyze
    actions:
      merge:
        method: merge
