version: 2.1
orbs:
  python: circleci/python@3.0.0

jobs:
  test:
    docker:
    # [[[cog
    # import cog
    # with open(".python-version") as f:
    #   cog.out(f"- image: cimg/python:{f.read().strip()}")
    # ]]]
    - image: cimg/python:3.12.5
    # [[[end]]] (checksum: fc0a16aa4f24e437fe39c7afd2bab265)
    steps:
    - checkout
    - restore_cache:
        key: v3-deps-{{ checksum "requirements.dev.txt" }}-{{ checksum "requirements.txt" }}
    - python/install-packages:
        pip-dependency-file: requirements.dev.txt
        pkg-manager: pip
    - save_cache:
        key: v3-deps-{{ checksum "requirements.dev.txt" }}-{{ checksum "requirements.txt" }}
        paths:
        - /home/circleci/.local/share/virtualenvs
        - /home/circleci/.cache/pip
    - run:
        name: Run tests
        command: python -m pytest

workflows:
  tests:
    jobs:
    - test
