# Generated by Django 4.0.2 on 2022-03-30 07:24

from django.db import migrations
import pages.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_formpage_alter_homepage_body_alter_infopage_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='formpage',
            name='body',
            field=wagtail.fields.StreamField([('Callout', wagtail.blocks.StructBlock([('headline', wagtail.blocks.CharBlock()), ('subline', wagtail.blocks.CharBlock())])), ('InfoPod', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock()), ('paragraph', wagtail.blocks.CharBlock(help_text='Optional', required=False)), ('page', wagtail.blocks.PageChooserBlock(required=False))]))), ('Paragraph', wagtail.blocks.RichTextBlock())], blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('Callout', wagtail.blocks.StructBlock([('headline', wagtail.blocks.CharBlock()), ('subline', wagtail.blocks.CharBlock())])), ('InfoPod', pages.blocks.FlexBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock()), ('paragraph', wagtail.blocks.CharBlock(help_text='Optional', required=False)), ('page', wagtail.blocks.PageChooserBlock(required=False))]))), ('Paragraph', wagtail.blocks.RichTextBlock()), ('Projects', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('body', wagtail.blocks.RichTextBlock(required=False)), ('projects', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(page_type=['projects.Project'])))]))]),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='body',
            field=wagtail.fields.StreamField([('Callout', wagtail.blocks.StructBlock([('headline', wagtail.blocks.CharBlock()), ('subline', wagtail.blocks.CharBlock())])), ('InfoPod', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock()), ('paragraph', wagtail.blocks.CharBlock(help_text='Optional', required=False)), ('page', wagtail.blocks.PageChooserBlock(required=False))]))), ('Paragraph', wagtail.blocks.RichTextBlock())]),
        ),
    ]
