# Generated by Django 4.0.2 on 2022-03-30 07:54

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.blocks.static_block
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_formpage_intro_formpage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='body',
            field=wagtail.core.fields.StreamField([('Callout', wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock()), ('subline', wagtail.core.blocks.CharBlock())])), ('InfoPod', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.core.blocks.CharBlock()), ('paragraph', wagtail.core.blocks.CharBlock(help_text='Optional', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(required=False))]))), ('Paragraph', wagtail.core.blocks.RichTextBlock()), ('Form', wagtail.core.blocks.static_block.StaticBlock(admin_text='The form', template='pages/blocks/form.html'))], blank=True),
        ),
    ]
