# Generated by Django 4.0.2 on 2022-03-30 18:36

from django.db import migrations, models
import wagtail.blocks
import wagtail.blocks.static_block
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_formpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='submit_button',
            field=models.CharField(default='Submit', max_length=255),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='body',
            field=wagtail.fields.StreamField([('Callout', wagtail.blocks.StructBlock([('headline', wagtail.blocks.CharBlock()), ('subline', wagtail.blocks.CharBlock())])), ('InfoPod', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock()), ('paragraph', wagtail.blocks.CharBlock(help_text='Optional', required=False)), ('page', wagtail.blocks.PageChooserBlock(required=False))]))), ('Paragraph', wagtail.blocks.RichTextBlock()), ('Form', wagtail.blocks.static_block.StaticBlock(admin_text='The form', icon='form', template='pages/blocks/form.html')), ('Map', wagtail.blocks.StructBlock([('latitude', wagtail.blocks.FloatBlock()), ('longitude', wagtail.blocks.FloatBlock())])), ('Row', wagtail.blocks.StreamBlock([('Form', wagtail.blocks.static_block.StaticBlock(admin_text='The form', icon='form', template='pages/blocks/form.html')), ('Map', wagtail.blocks.StructBlock([('latitude', wagtail.blocks.FloatBlock()), ('longitude', wagtail.blocks.FloatBlock())]))]))], blank=True),
        ),
    ]
