# Generated by Django 4.0.2 on 2022-03-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_formpage_submit_button_alter_formpage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formpage',
            old_name='submit_button',
            new_name='submit_text',
        ),
    ]
