# Generated by Django 4.0.2 on 2022-03-30 20:06

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_rename_submit_button_formpage_submit_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='body',
            field=wagtail.fields.StreamField([('Callout', wagtail.blocks.StructBlock([('headline', wagtail.blocks.CharBlock()), ('subline', wagtail.blocks.CharBlock())])), ('InfoPod', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock()), ('paragraph', wagtail.blocks.CharBlock(help_text='Optional', required=False)), ('page', wagtail.blocks.PageChooserBlock(required=False))]))), ('Paragraph', wagtail.blocks.RichTextBlock()), ('Form', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False))])), ('Map', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('latitude', wagtail.blocks.FloatBlock()), ('longitude', wagtail.blocks.FloatBlock())])), ('Row', wagtail.blocks.StreamBlock([('Form', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False))])), ('Map', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('latitude', wagtail.blocks.FloatBlock()), ('longitude', wagtail.blocks.FloatBlock())]))]))], blank=True),
        ),
    ]
