# Generated by Django 4.0.2 on 2022-04-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_socialmediasettings_contactsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsettings',
            name='facebook',
            field=models.URLField(default='', help_text='Your Facebook page URL'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='instagram',
            field=models.CharField(default='', help_text='Your Instagram username, without the @', max_length=255),
        ),
        migrations.DeleteModel(
            name='SocialMediaSettings',
        ),
    ]
