# Generated by Django 4.0.2 on 2022-04-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_contactsettings_facebook_contactsettings_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsettings',
            name='phone_number',
            field=models.CharField(default='', help_text='Phone number to show in the footer', max_length=255),
        ),
    ]
