# Generated by Django 4.0.2 on 2022-04-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_rename_contactsettings_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_maps_api_key',
            field=models.CharField(default='', help_text='Google Maps API key', max_length=255),
        ),
    ]
