# Generated by Django 4.0.4 on 2022-05-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_sitesettings_google_maps_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='google_maps_api_key',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='checkatrade',
            field=models.CharField(default='', help_text='Your checkatrade link', max_length=255),
        ),
    ]
