# Generated by Django 4.1.7 on 2023-03-06 08:21

from django.db import migrations
import pages.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0020_alter_formfield_choices_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "Callout",
                        wagtail.blocks.StructBlock(
                            [("headline", wagtail.blocks.CharBlock()), ("subline", wagtail.blocks.CharBlock())]
                        ),
                    ),
                    (
                        "InfoPod",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.StructBlock(
                                [
                                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                                    ("title", wagtail.blocks.CharBlock()),
                                    ("paragraph", wagtail.blocks.CharBlock(help_text="Optional", required=False)),
                                    ("page", wagtail.blocks.PageChooserBlock(required=False)),
                                ]
                            )
                        ),
                    ),
                    ("Paragraph", wagtail.blocks.RichTextBlock()),
                    ("Form", wagtail.blocks.StructBlock([("title", wagtail.blocks.CharBlock(required=False))])),
                    (
                        "Map",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=False)),
                                ("latitude", wagtail.blocks.FloatBlock()),
                                ("longitude", wagtail.blocks.FloatBlock()),
                            ]
                        ),
                    ),
                    (
                        "Row",
                        wagtail.blocks.StreamBlock(
                            [
                                ("Form", wagtail.blocks.StructBlock([("title", wagtail.blocks.CharBlock(required=False))])),
                                (
                                    "Map",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("title", wagtail.blocks.CharBlock(required=False)),
                                            ("latitude", wagtail.blocks.FloatBlock()),
                                            ("longitude", wagtail.blocks.FloatBlock()),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "Callout",
                        wagtail.blocks.StructBlock(
                            [("headline", wagtail.blocks.CharBlock()), ("subline", wagtail.blocks.CharBlock())]
                        ),
                    ),
                    (
                        "InfoPod",
                        pages.blocks.FlexBlock(
                            wagtail.blocks.StructBlock(
                                [
                                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                                    ("title", wagtail.blocks.CharBlock()),
                                    ("paragraph", wagtail.blocks.CharBlock(help_text="Optional", required=False)),
                                    ("page", wagtail.blocks.PageChooserBlock(required=False)),
                                ]
                            )
                        ),
                    ),
                    ("Paragraph", wagtail.blocks.RichTextBlock()),
                    (
                        "Projects",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(max_length=255, required=True)),
                                ("body", wagtail.blocks.RichTextBlock(required=False)),
                                (
                                    "projects",
                                    wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(page_type=["projects.Project"])),
                                ),
                            ]
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="infopage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "Callout",
                        wagtail.blocks.StructBlock(
                            [("headline", wagtail.blocks.CharBlock()), ("subline", wagtail.blocks.CharBlock())]
                        ),
                    ),
                    (
                        "InfoPod",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.StructBlock(
                                [
                                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                                    ("title", wagtail.blocks.CharBlock()),
                                    ("paragraph", wagtail.blocks.CharBlock(help_text="Optional", required=False)),
                                    ("page", wagtail.blocks.PageChooserBlock(required=False)),
                                ]
                            )
                        ),
                    ),
                    ("Paragraph", wagtail.blocks.RichTextBlock()),
                ],
                use_json_field=True,
            ),
        ),
    ]
