name: Empty action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.py'

jobs:
  analyze-nothing:
    name: Analyze Nothing
    runs-on: ubuntu-latest
    steps:
      - run: echo "Nothing to analyze"